package cz.cvut.fel.sin.sintest.exception;

public class FightCannotHappenException extends RuntimeException {
    public FightCannotHappenException(String message) {
        super(message);
    }
}
